nastyCloud/Controllers/ChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using nastyCloud.Models;

namespace nastyCloud.Controllers
{
    public class ChatController : Controller
    {
        private readonly CloudContext _db;

        public ChatController(CloudContext context)
        {
            _db = context;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            User user = await _db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);
            return View(user);
        }
    }
}

nastyCloud/Controllers/SearchController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using nastyCloud.Models;
using System.Threading.Tasks;
using nastyCloud.ViewModels;

namespace nastyCloud.Controllers
{
    public class SearchController : Controller
    {
        private CloudContext db;

        public SearchController(CloudContext context)
        {
            this.db = context;
        }

        [Authorize]
        public async Task<IActionResult> Index([FromQuery] string search)
        {
            User user = await db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);
            ViewBag.isAdmin = user.isAdmin;
            var files = search != null ? db.UserFiles.Where(file => file.ClientName.StartsWith(search)) : db.UserFiles;
            if (user.isAdmin)
            {
                var users = search != null ? db.Users.Where(searchUser => searchUser.Nickname.StartsWith(search)) : db.Users;
                var viewAdminSearch = new AdminSearchViewModel() { UserFiles = files.ToList(), Users = users.ToList() };
                return View(viewAdminSearch);
            }
            files = files.Where(file => file.isPublic);
            var viewUserSearch = new AdminSearchViewModel() { UserFiles = files.ToList(), Users = null };
            return View(viewUserSearch);
        }
    }
}

nastyCloud/Views/Shared/Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper "nastyCloud.TagHelpers.AuthorTagHelper, nastyCloud"

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Home</title>
    <link rel="stylesheet" href="~/css/body.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark d-flex justify-content-between mb-3">
        <form class="form-inline p-2" asp-action="Index" asp-controller="Search" method="GET">
            <input class="form-control mr-sm-2" type="text" placeholder="@Localizer["Search"]" name="search">
            <button class="btn btn-success" type="submit">@Localizer["Search"]</button>
        </form>
        <span class="nav-item dropdown p-2">
            <span class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                @Localizer["Menu"]
            </span>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-action="Index" asp-controller="Chat">@Localizer["Chat"]</a>
                <a class="dropdown-item" asp-action="Logout" asp-controller="Account">@Localizer["Log Out"]</a>
                <author class="dropdown-item"></author>
            </div>
        </span>
    </nav>

    <div class="container body-content">
        <div>
            @await Html.PartialAsync("_SelectLanguagePartial")
        </div>

        @RenderBody()
    </div>
</body>
</html>

nastyCloud/Views/Shared/_SelectLanguagePartial.cshtml
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetLanguage" asp-route-returnUrl="@returnUrl"
          method="post" class="form-horizontal" role="form">
        <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language"]</label>
        <select name="culture"
                onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems"></select>
    </form>
</div>